# Generated by Django 4.2.16 on 2025-10-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_table_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
