# Generated by Django 5.2.8 on 2025-12-12 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_order_table_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('paid', 'Paid'), ('customer_paid', 'Customer Paid')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='TableQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qr_codes/')),
                ('url', models.URLField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='foodapp.table')),
            ],
        ),
    ]
