# Generated by Django 5.2.8 on 2025-12-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_table_created_by_alter_order_status_tableqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
