# Generated by Django 5.2.8 on 2025-12-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_delete_scanner_remove_table_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
